from django.utils.safestring import mark_safe

def switch_find_team_by_abbr(y):
    switch = {
        'MIN' : 'Minnesota Vikings',
        'ARI' : 'Arizona Cardinals',
        'ATL' : 'Atlanta Falcons',
        'BAL' : 'Baltimore Ravens',
        'BUF' : 'Buffalo Bills',
        'CAR' : 'Carolina Panthers',
        'CHI' : 'Chicago Bears',
        'CIN' : 'Cincinnati Bengals',
        'CLE' : 'Cleveland Browns',
        'DAL' : 'Dallas Cowboys',
        'DEN' : 'Denver Broncos',
        'DET' : 'Detroit Lions',
        'GB' : 'Green Bay Packers',
        'HOU' : 'Houston Texans',
        'IND' : 'Indianapolis Colts',
        'JAC' : 'Jacksonville Jaguars',
        'KC' : 'Kansas City Chiefs',
        'MIA' : 'Miami Dolphins',
        'NE' : 'New England Patriots',
        'NO' : 'New Orleans Saints',
        'NYG' : 'New York Giants',
        'NYJ' : 'New York Jets',
        'OAK' : 'Oakland Raiders',
        'PHI' : 'Philadelphia Eagles',
        'PIT' : 'Pittsburgh Steelers',
        'LAC' : 'Los Angeles Chargers',
        'SEA' : 'Seattle Seahawks',
        'SF' : 'San Francisco 49ers',
        'LA' : 'St. Louis Rams',
        'TB' : 'Tampa Bay Buccaneers',
        'TEN' : 'Tennessee Titans',
        'WAS' : 'Washington Redskins'
    }
    return switch.get(y)

def switch_find_img(x):
    switch = {
        'Dallas' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/dal.png?w=45&amp;h=45&amp;transparent=true">'),
        'New York Giants' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/nyg.png?w=45&amp;h=45&amp;transparent=true">'),
        'New York Jets' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/nyj.png?w=45&amp;h=45&amp;transparent=true">'),
        'Philadelphia' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/phi.png?w=45&amp;h=45&amp;transparent=true">'),
        'Washington' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/was.png?w=45&amp;h=45&amp;transparent=true">'),
        'Buffalo' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/buf.png?w=45&amp;h=45&amp;transparent=true">'),
        'Miami' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/mia.png?w=45&h=45&transparent=true">'),
        'New England' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/ne.png?w=45&h=45&transparent=true">'),
        'Arizona' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/ari.png?w=45&h=45&transparent=true">'),
        'San Francisco' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/sf.png?w=45&h=45&transparent=true">'),
        'Seattle' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/sea.png?w=45&h=45&transparent=true">'),
        'Los Angeles Rams' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/stl.png?w=45&h=45&transparent=true">'),
        'Denver' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/den.png?w=45&h=45&transparent=true">'),
        'Kansas City' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/kc.png?w=45&h=45&transparent=true">'),
        'Oakland' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/oak.png?w=45&h=45&transparent=true">'),
        'Los Angeles Chargers' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/sd.png?w=45&h=45&transparent=true">'),
        'Chicago' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/chi.png?w=45&h=45&transparent=true">'),
        'Detroit' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/det.png?w=45&h=45&transparent=true">'),
        'Green Bay' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/gb.png?w=45&h=45&transparent=true">'),
        'Minnesota' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/min.png?w=45&h=45&transparent=true">'),
        'Baltimore' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/bal.png?w=45&h=45&transparent=true">'),
        'Cincinnati' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/cin.png?w=45&h=45&transparent=true">'),
        'Cleveland' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/cle.png?w=45&h=45&transparent=true">'),
        'Pittsburgh' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/pit.png?w=45&h=45&transparent=true">'),
        'Atlanta' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/atl.png?w=45&h=45&transparent=true">'),
        'Carolina' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/car.png?w=45&h=45&transparent=true">'),
        'New Orleans' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/no.png?w=45&h=45&transparent=true">'),
        'Tampa Bay' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/tb.png?w=45&h=45&transparent=true">'),
        'Houston' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/hou.png?w=45&h=45&transparent=true">'),
        'Indianapolis' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/ind.png?w=45&h=45&transparent=true">'),
        'Jacksonville' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/jax.png?w=45&h=45&transparent=true">'),
        'Tennessee' : mark_safe('<img src="http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/ten.png?w=45&h=45&transparent=true">'),
    }
    return switch.get(x)
